CXXFLAGS += -Wall -pedantic -std=c++14 -DAPPLE -DDEBUG
FRAMEWORKS := -framework Cocoa -framework OpenGL -framework IOKit -framework CoreVideo
LIBS := -L /usr/local/lib -lGLEW -lglfw3
INCLUDE := -I /usr/local/include

all:
	$(CXX) main.cpp $(CXXFLAGS) $(FRAMEWORKS) $(LIBS) $(INCLUDE) -o program.out
